version: "3.9"
services:
  strive:
    build: .
    tty: true
    restart: on-failure
    volumes:
      - .:/strive
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

